[package]
name = "notula"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.31.1"
eframe = { version = "0.31.1", features = ["default"] }
env_logger = "0.11.8"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "shellapi", "impl-default"] }
